name: Build IUP, CD, IM with Lua
on:
  push:
  workflow_dispatch:

env:
  LUA_VERSION: "5.4.8"
  IUP_VERSION: "3.32"
  CD_VERSION: "5.14"
  IM_VERSION: "3.15"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-tools
            make
            tar
            wget
            sed

      - name: Create build directory
        run: |
          mkdir -p /d/build /d/dist/{bin,lib,include}

      - name: Check GCC version
        run: |
          cd /d/build
          gcc --version > gcc_version.txt

      - name: Download Lua source
        run: |
          cd /d/build
          wget --user-agent="Wget" -O lua-${{ env.LUA_VERSION }}.tar.gz https://www.lua.org/ftp/lua-${{ env.LUA_VERSION }}.tar.gz
          tar -xzf lua-${{ env.LUA_VERSION }}.tar.gz
          mv lua-${{ env.LUA_VERSION }} lua54

      - name: Build Lua
        run: |
          cd /d/build/lua54/src
          sed -i 's|LUA_CDIR"?.dll;"|LUA_CDIR"?.dll;" LUA_CDIR"?54.dll;"|' luaconf.h
          make mingw

          mkdir -p /d/build/lua54/install/{bin,lib,include}
          cp lua.exe /d/build/lua54/install/bin/lua.exe
          cp luac.exe /d/build/lua54/install/bin/
          cp lua54.dll /d/build/lua54/install/bin/
          cp lua54.dll /d/build/lua54/install/lib/

          gendef lua54.dll
          dlltool --dllname lua54.dll --def lua54.def --output-lib /d/build/lua54/install/lib/liblua54.a
          cp lua.h luaconf.h lualib.h lauxlib.h lua.hpp /d/build/lua54/install/include/

          cd /d/build

      - name: Download IUP dependencies from SourceForge
        run: |
          cd /d/build
          wget --user-agent="Wget" -O zlib.tar.gz "https://sourceforge.net/projects/iup/files/${{ env.IUP_VERSION }}/Docs%20and%20Sources/zlib-1.2.11_Sources.tar.gz/download"
          wget --user-agent="Wget" -O freetype.tar.gz "https://sourceforge.net/projects/iup/files/${{ env.IUP_VERSION }}/Docs%20and%20Sources/freetype-2.10.2_Sources.tar.gz/download"
          wget --user-agent="Wget" -O ftgl.tar.gz "https://sourceforge.net/projects/iup/files/${{ env.IUP_VERSION }}/Docs%20and%20Sources/ftgl-2.1.5_Sources.tar.gz/download"
          wget --user-agent="Wget" -O im.tar.gz "https://sourceforge.net/projects/imtoolkit/files/${{ env.IM_VERSION }}/Docs%20and%20Sources/im-${{ env.IM_VERSION }}_Sources.tar.gz/download"
          wget --user-agent="Wget" -O cd.tar.gz "https://sourceforge.net/projects/canvasdraw/files/${{ env.CD_VERSION }}/Docs%20and%20Sources/cd-${{ env.CD_VERSION }}_Sources.tar.gz/download"
          wget --user-agent="Wget" -O iup.tar.gz "https://sourceforge.net/projects/iup/files/${{ env.IUP_VERSION }}/Docs%20and%20Sources/iup-${{ env.IUP_VERSION }}_Sources.tar.gz/download"

      - name: Extract all sources
        run: |
          cd /d/build
          tar -xzf zlib.tar.gz
          tar -xzf freetype.tar.gz
          tar -xzf ftgl.tar.gz
          tar -xzf im.tar.gz
          tar -xzf cd.tar.gz
          tar -xzf iup.tar.gz

      - name: Patch Tecmake files for MSYS2
        run: |
          cd /d/build
          find . -name "tecmakewin.mak" -exec sed -i \
            -e 's|x:/lng/mingw4_64|/mingw64|g' \
            -e 's|x:/lng/dllw4_64|/mingw64|g' \
            -e 's|\$\(TEC_TOOLCHAIN\)gcc|gcc|g' \
            -e 's|\$\(TEC_TOOLCHAIN\)g++|g++|g' \
            -e 's|\$\(TEC_TOOLCHAIN\)ar|ar|g' \
            -e 's|\$\(TEC_TOOLCHAIN\)ranlib|ranlib|g' \
            {} \;

      - name: Build zlib
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export NO_DEPEND=Yes
          export TECTOOLS_HOME=/d/build

          cd /d/build/zlib/src
          make

          cp ../lib/dllw4_64/*.dll /d/dist/bin/
          cp ../lib/dllw4_64/*.a /d/dist/lib/
          cd /d/build

      - name: Build freetype
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export NO_DEPEND=Yes

          cd /d/build/freetype/src
          make

          cp ../lib/dllw4_64/*.dll /d/dist/bin/
          cp ../lib/dllw4_64/*.a /d/dist/lib/
          cd /d/build

      - name: Build ftgl
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export NO_DEPEND=Yes

          cd /d/build/ftgl/src
          make

          cp ../lib/dllw4_64/*.dll /d/dist/bin/ 2>/dev/null || true
          cp ../lib/dllw4_64/*.a /d/dist/lib/ 2>/dev/null || true
          cd /d/build

      - name: Build IM
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export USE_LUA_VERSION=54
          export NO_DEPEND=Yes
          export TECTOOLS_HOME=/d/build
          export LUA_INC=/d/build/lua54/install/include
          export LUA_LIB=/d/build/lua54/install/lib
          export LUA_BIN=/d/build/lua54/install/bin

          cd /d/build/im/src
          make im im_jp2 im_process im_process_omp im_avi

          if [ ! -f ../lib/dllw4_64/im.dll ]; then
            echo "ERROR: Core IM DLL failed to build"
            exit 1
          fi

          make imlua5 imlua_process5 imlua_jp25 imlua_process_omp5 imlua_avi5

          find ../lib/dllw4_64 -name "*.dll" -exec cp -v {} /d/dist/bin/ \;
          find ../lib/dllw4_64 -name "*.a" -exec cp -v {} /d/dist/lib/ \;
          cd /d/build

      - name: Build CD
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export USE_LUA_VERSION=54
          export NO_DEPEND=Yes
          export TECTOOLS_HOME=/d/build
          export LUA_INC=/d/build/lua54/install/include
          export LUA_LIB=/d/build/lua54/install/lib
          export LUA_BIN=/d/build/lua54/install/bin
          export FLAGS="-Wno-error=incompatible-pointer-types"

          cd /d/build/cd/src
          make cd cdgl cdim cdcontextplus

          if [ ! -f ../lib/dllw4_64/cd.dll ]; then
            echo "ERROR: Core CD DLL failed to build"
            exit 1
          fi

          make cdlua5 cdluagl5 cdluaim5 cdluacontextplus5

          find ../lib/dllw4_64 -name "*.dll" -exec cp -v {} /d/dist/bin/ \;
          find ../lib/dllw4_64 -name "*.a" -exec cp -v {} /d/dist/lib/ \;
          cd /d/build

      - name: Build IUP
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export USE_LUA_VERSION=54
          export NO_DEPEND=Yes
          export TECTOOLS_HOME=/d/build
          export LUA_INC=/d/build/lua54/install/include
          export LUA_LIB=/d/build/lua54/install/lib
          export LUA_BIN=/d/build/lua54/install/bin
          export FLAGS="-Wno-error=incompatible-pointer-types"

          cd /d/build/iup
          make iup iupcd iupcontrols iupgl iupglcontrols iup_plot iup_scintilla iupim iupimglib iupole

          cd src
          TEC_UNAME=mingw4_64 make -f ../tecmakewin.mak MF=iupstub
          mkdir -p ../lib/dllw4_64
          mv ../lib/mingw4_64/libiupstub.a ../lib/dllw4_64/
          cd ..

          make -C srclua5 -k || true
          make iupluaconsole

          if [ ! -f lib/dllw4_64/iup.dll ]; then
            echo "ERROR: Core IUP DLL failed"
            exit 1
          fi

          find lib/dllw4_64 -name "*.dll" -exec cp -v {} /d/dist/bin/ \;
          find lib/dllw4_64 -name "*.a" -exec cp -v {} /d/dist/lib/ \;
          find bin -name "*.exe" -exec cp -v {} /d/dist/bin/ \;
          cd /d/build

      - name: Package Results
        run: |
          echo "Copying Lua..."
          cp -r /d/build/lua54/install/* /d/dist/

          echo "Copying headers..."
          cp -r /d/build/iup/include/* /d/dist/include/
          cp -r /d/build/cd/include/* /d/dist/include/
          cp -r /d/build/im/include/* /d/dist/include/

          echo "=== Package contents ==="
          echo "Executables:"
          ls -lah /d/dist/bin/*.exe 2>/dev/null || true
          echo ""
          echo "DLLs:"
          ls -lah /d/dist/bin/*.dll 2>/dev/null | head -50
          echo ""
          echo "Import libraries:"
          ls -lah /d/dist/lib/*.a 2>/dev/null | head -20

      - name: Set padded build number
        run: |
          echo "PADDED_BUILD=$(printf '%04d' ${{ github.run_number }})" >> $GITHUB_ENV

      - name: Create Archive
        # tar -czf iup-cd-im-lua-${{ env.IUP_VERSION }}-build${{ env.PADDED_BUILD }}-win64.tar.gz -C /d dist/
        run: |
          cd $GITHUB_WORKSPACE
          cp -r dist iup
          tar -czf iup-windows-amd64.tar.gz -C /d iup/
          ls -lh *.tar.gz

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: iup-cd-im-lua-${{ env.IUP_VERSION }}-build${{ env.PADDED_BUILD }}-win64
          path: iup-cd-im-lua-${{ env.IUP_VERSION }}-build${{ env.PADDED_BUILD }}-win64.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          # files: iup-cd-im-lua-${{ env.IUP_VERSION }}-build${{ env.PADDED_BUILD }}-win64.tar.gz
          files: iup-windows-amd64.tar.gz
          tag_name: ${{ env.IUP_VERSION }}-build-${{ env.PADDED_BUILD }}
          name: IUP/CD/IM ${{ env.IUP_VERSION }} Build ${{ env.PADDED_BUILD }}
          body: |
            Automated build of IUP/CD/IM ${{ env.IUP_VERSION }} with Lua ${{ env.LUA_VERSION }} for Windows x64

            Includes:
            - IUP ${{ env.IUP_VERSION }}
            - CD ${{ env.CD_VERSION }}
            - IM ${{ env.IM_VERSION }}
            - Lua ${{ env.LUA_VERSION }} (custom built with ?54.dll pattern support)
            - lua.exe (Lua interpreters)
            - iuplua54.exe (Lua interpreter with IUP)
            - All dependencies (zlib, freetype, ftgl)
            - Lua bindings for IUP, CD, IM

            Executables and DLLs are in the bin/ directory
            Import libraries (.a) are in the lib/ directory
            Headers are in the include/ directory

            Note: require("iuplua") works with both iuplua.dll and iuplua54.dll

            Built with MinGW-w64 on MSYS2
            Build number: ${{ env.PADDED_BUILD }}
            Commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}