name: Build IUP, CD, IM with Lua (DLL)
on:
  push:
  workflow_dispatch:

env:
  LUA_VERSION: "5.4.8"
  IUP_VERSION: "3.32"
  CD_VERSION: "5.14"
  IM_VERSION: "3.15"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            make
            tar
            wget
            sed

      - name: Create build directory
        run: |
          mkdir -p /d/build
          cd /d/build

      - name: Download Lua source
        run: |
          cd /d/build
          wget --user-agent="Wget" -O lua-${{ env.LUA_VERSION }}.tar.gz https://www.lua.org/ftp/lua-${{ env.LUA_VERSION }}.tar.gz
          tar -xzf lua-${{ env.LUA_VERSION }}.tar.gz
          mv lua-${{ env.LUA_VERSION }} lua54

      - name: Download IUP dependencies from SourceForge
        run: |
          cd /d/build
          wget --user-agent="Wget" -O zlib.tar.gz "https://sourceforge.net/projects/iup/files/${{ env.IUP_VERSION }}/Docs%20and%20Sources/zlib-1.2.11_Sources.tar.gz/download"
          wget --user-agent="Wget" -O freetype.tar.gz "https://sourceforge.net/projects/iup/files/${{ env.IUP_VERSION }}/Docs%20and%20Sources/freetype-2.10.2_Sources.tar.gz/download"
          wget --user-agent="Wget" -O ftgl.tar.gz "https://sourceforge.net/projects/iup/files/${{ env.IUP_VERSION }}/Docs%20and%20Sources/ftgl-2.1.5_Sources.tar.gz/download"
          wget --user-agent="Wget" -O im.tar.gz "https://sourceforge.net/projects/imtoolkit/files/${{ env.IM_VERSION }}/Docs%20and%20Sources/im-${{ env.IM_VERSION }}_Sources.tar.gz/download"
          wget --user-agent="Wget" -O cd.tar.gz "https://sourceforge.net/projects/canvasdraw/files/${{ env.CD_VERSION }}/Docs%20and%20Sources/cd-${{ env.CD_VERSION }}_Sources.tar.gz/download"
          wget --user-agent="Wget" -O iup.tar.gz "https://sourceforge.net/projects/iup/files/${{ env.IUP_VERSION }}/Docs%20and%20Sources/iup-${{ env.IUP_VERSION }}_Sources.tar.gz/download"

      - name: Extract all sources
        run: |
          cd /d/build
          tar -xzf zlib.tar.gz
          tar -xzf freetype.tar.gz
          tar -xzf ftgl.tar.gz
          tar -xzf im.tar.gz
          tar -xzf cd.tar.gz
          tar -xzf iup.tar.gz
          ls -la

      - name: Patch Tecmake files for MSYS2
        run: |
          cd /d/build
          find . -name "tecmakewin.mak" -exec sed -i \
            -e 's|x:/lng/mingw4_64|/mingw64|g' \
            -e 's|x:/lng/dllw4_64|/mingw64|g' \
            -e 's|\$\(TEC_TOOLCHAIN\)gcc|gcc|g' \
            -e 's|\$\(TEC_TOOLCHAIN\)g++|g++|g' \
            -e 's|\$\(TEC_TOOLCHAIN\)ar|ar|g' \
            -e 's|\$\(TEC_TOOLCHAIN\)ranlib|ranlib|g' \
            {} \;
          echo "Tecmake files patched for MSYS2"

      - name: Build Lua
        run: |
          cd /d/build/lua54
          make PLAT=mingw
          make PLAT=mingw INSTALL_TOP=/d/build/lua54/install install
          cd install/lib
          cp liblua.a liblua54.a
          cd /d/build

      - name: Build zlib
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export USE_LUA_VERSION=54
          export NO_DEPEND=Yes
          export TECTOOLS_HOME=/d/build
          cd /d/build/zlib/src
          make
          cd ../..

      - name: Build freetype
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export NO_DEPEND=Yes
          cd /d/build/freetype/src
          make
          cd ../..

      - name: Build ftgl
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export NO_DEPEND=Yes
          cd /d/build/ftgl/src
          make
          cd ../..

      - name: Build IM
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export USE_LUA_VERSION=54
          export NO_DEPEND=Yes
          export TECTOOLS_HOME=/d/build
          export LUA_INC=/d/build/lua54/install/include
          export LUA_LIB=/d/build/lua54/install/lib
          
          # Build core IM libraries
          cd /d/build/im/src
          make im im_process im_jp2
          
          if [ ! -f ../lib/dllw4_64/im.dll ]; then
            echo "ERROR: Core IM DLL failed to build"
            exit 1
          fi
          echo "Core IM DLL built successfully"
          
          # Build Lua bindings
          echo "=== Building Lua bindings ==="
          make imlua5 imlua_process5 imlua_jp25
          
          if [ $? -ne 0 ]; then
            echo "ERROR: Lua bindings build failed"
            exit 1
          fi
          
          echo "IM Lua bindings built successfully"
          cd /d/build

      - name: Build CD
        run: |
          export TEC_UNAME=dllw4_64
          export TEC_TOOLCHAIN=""
          export USE_LUA_VERSION=54
          export NO_DEPEND=Yes
          export TECTOOLS_HOME=/d/build
          export LUA_INC=/d/build/lua54/install/include
          export LUA_LIB=/d/build/lua54/install/lib
          export FLAGS="-Wno-error=incompatible-pointer-types"
          
          cd /d/build/cd/src
          
          # Build core CD modules (excluding cdpdf which requires pdflib)
          echo "=== Building CD core libraries ==="
          make cd cdgl cdim cdcontextplus
          
          if [ ! -f ../lib/dllw4_64/cd.dll ]; then
            echo "ERROR: Core CD DLL failed to build"
            exit 1
          fi
          echo "Core CD libraries built successfully"
          
          # Build CD Lua bindings (excluding cdluapdf5 which requires pdflib)
          echo "=== Building CD Lua bindings ==="
          make cdlua5 cdluagl5 cdluaim5 cdluacontextplus5
          
          if [ $? -ne 0 ]; then
            echo "ERROR: CD Lua bindings build failed"
            exit 1
          fi
          
          echo "CD Lua bindings built successfully"
          cd /d/build

      - name: Build IUP
        run: |
          export TEC_UNAME=mingw4_64
          export TEC_TOOLCHAIN=""
          export USE_LUA_VERSION=54
          export NO_DEPEND=Yes
          export TECTOOLS_HOME=/d/build
          export LUA_INC=/d/build/lua54/install/include
          export LUA_LIB=/d/build/lua54/install/lib
          export FLAGS="-Wno-error=incompatible-pointer-types"
          cd /d/build/iup
          # Build only libraries, skip example applications
          make iup iupole iupim iupimglib iuplua54 iupluaim54
          cd ..

      - name: Verify Build Results
        run: |
          echo "=== Checking built libraries ==="
          echo "--- IUP DLLs ---"
          find /d/build/iup/lib/dllw4_64 -name "*.dll" 2>/dev/null | head -20
          echo "--- CD DLLs ---"
          find /d/build/cd/lib/dllw4_64 -name "*.dll" 2>/dev/null | head -20
          echo "--- IM DLLs ---"
          find /d/build/im/lib/dllw4_64 -name "*.dll" 2>/dev/null | head -20

      - name: Set padded build number
        run: |
          echo "PADDED_BUILD=$(printf '%04d' ${{ github.run_number }})" >> $GITHUB_ENV

      - name: Package Results
        run: |
          mkdir -p /d/dist/{lib,include,bin}
          
          echo "Copying Lua..."
          cp -r /d/build/lua54/install/* /d/dist/
          
          echo "Copying IUP DLLs and import libraries..."
          find /d/build/iup/lib/dllw4_64 -type f \( -name "*.dll" -o -name "*.a" \) -exec cp -v {} /d/dist/bin/ \;
          
          echo "Copying CD DLLs and import libraries..."
          find /d/build/cd/lib/dllw4_64 -type f \( -name "*.dll" -o -name "*.a" \) -exec cp -v {} /d/dist/bin/ \;
          
          echo "Copying IM DLLs and import libraries..."
          find /d/build/im/lib/dllw4_64 -type f \( -name "*.dll" -o -name "*.a" \) -exec cp -v {} /d/dist/bin/ \;
          
          echo "Copying headers..."
          cp -r /d/build/iup/include/* /d/dist/include/ 2>/dev/null || true
          cp -r /d/build/cd/include/* /d/dist/include/ 2>/dev/null || true
          cp -r /d/build/im/include/* /d/dist/include/ 2>/dev/null || true
          
          echo "=== Package contents ==="
          echo "DLLs:"
          ls -lah /d/dist/bin/*.dll 2>/dev/null | head -30
          echo "Import libraries:"
          ls -lah /d/dist/bin/*.a 2>/dev/null | head -10
          
          cd /d
          tar -czf iup-cd-im-lua-${{ env.IUP_VERSION }}-build${{ env.PADDED_BUILD }}-win64-dll.tar.gz dist/

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: iup-cd-im-lua-${{ env.IUP_VERSION }}-build${{ env.PADDED_BUILD }}-win64-dll
          path: /d/iup-cd-im-lua-${{ env.IUP_VERSION }}-build${{ env.PADDED_BUILD }}-win64-dll.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: /d/iup-cd-im-lua-${{ env.IUP_VERSION }}-build${{ env.PADDED_BUILD }}-win64-dll.tar.gz
          tag_name: ${{ env.IUP_VERSION }}-build-${{ env.PADDED_BUILD }}
          name: IUP/CD/IM ${{ env.IUP_VERSION }} Build ${{ env.PADDED_BUILD }} (DLL)
          body: |
            Automated build of IUP/CD/IM ${{ env.IUP_VERSION }} with Lua ${{ env.LUA_VERSION }} for Windows x64 (DLL version)

            Includes:
            - IUP ${{ env.IUP_VERSION }} (DLL)
            - CD ${{ env.CD_VERSION }} (DLL)
            - IM ${{ env.IM_VERSION }} (DLL) - core, process, jp2
            - Lua ${{ env.LUA_VERSION }}
            - All dependencies (zlib, freetype, ftgl)
            - Lua bindings for IUP, CD, IM

            DLLs and import libraries (.a) are in the bin/ directory
            Headers are in the include/ directory

            Note: Excluded modules - im_wmv, im_capture, im_avi, im_fftw3

            Built with MinGW-w64 on MSYS2
            Build number: ${{ env.PADDED_BUILD }}
            Commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}